"""delete notificationwatered

Revision ID: 14de38830cd3
Revises: adfbc885e340
Create Date: 2026-04-18 18:05:12.253707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14de38830cd3'
down_revision: Union[str, Sequence[str], None] = 'adfbc885e340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'watered')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('watered', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
