"""add use_sensor to plant

Revision ID: 2b8aacb11c5a
Revises: 9fb5eeb580d6
Create Date: 2026-04-16 15:49:40.745440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8aacb11c5a'
down_revision: Union[str, Sequence[str], None] = '9fb5eeb580d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('use_sensor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'use_sensor')
    # ### end Alembic commands ###
