"""add fruit veg and edible booleans

Revision ID: 3ac2af0afa61
Revises: ae5430c11581
Create Date: 2026-04-27 17:44:24.314881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3ac2af0afa61"
down_revision: Union[str, Sequence[str], None] = "ae5430c11581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plant_species", sa.Column("is_edible", sa.Boolean(), nullable=True))
    op.add_column("plant_species", sa.Column("is_fruit", sa.Boolean(), nullable=True))
    op.add_column("plant_species", sa.Column("is_veg", sa.Boolean(), nullable=True))
    op.drop_column("plant_species", "edible")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plant_species",
        sa.Column("edible", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    )
    op.drop_column("plant_species", "is_veg")
    op.drop_column("plant_species", "is_fruit")
    op.drop_column("plant_species", "is_edible")
    # ### end Alembic commands ###
