"""expand plant species cache

Revision ID: 8ad46fbd478e
Revises: 3ac2af0afa61
Create Date: 2026-05-11 13:34:34.830210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad46fbd478e'
down_revision: Union[str, Sequence[str], None] = '3ac2af0afa61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_species', sa.Column('other_names', sa.String(length=500), nullable=True))
    op.add_column('plant_species', sa.Column('plant_type', sa.String(length=100), nullable=True))
    op.add_column('plant_species', sa.Column('description', sa.String(), nullable=True))
    op.add_column('plant_species', sa.Column('cuisine', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('medicinal', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('poisonous_to_humans', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('poisonous_to_pets', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('care_level', sa.String(length=50), nullable=True))
    op.add_column('plant_species', sa.Column('watering', sa.String(length=50), nullable=True))
    op.add_column('plant_species', sa.Column('drought_tolerant', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('salt_tolerant', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('thorny', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('invasive', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('tropical', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('indoor', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('hardiness', sa.String(length=100), nullable=True))
    op.add_column('plant_species', sa.Column('hardiness_location', sa.String(length=255), nullable=True))
    op.add_column('plant_species', sa.Column('max_height_ft', sa.Float(), nullable=True))
    op.add_column('plant_species', sa.Column('max_width_ft', sa.Float(), nullable=True))
    op.add_column('plant_species', sa.Column('default_image_url', sa.String(), nullable=True))
    op.add_column('plant_species', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('plant_species', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('plant_species', 'external_species_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('plant_species', 'scientific_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('plant_species', 'common_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('plant_species', 'growth_rate',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('plant_species', 'pest_susceptibility',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_plant_species_external_species_id'), 'plant_species', ['external_species_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_species_external_species_id'), table_name='plant_species')
    op.alter_column('plant_species', 'pest_susceptibility',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('plant_species', 'growth_rate',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('plant_species', 'common_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('plant_species', 'scientific_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('plant_species', 'external_species_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('plant_species', 'created_at')
    op.drop_column('plant_species', 'thumbnail_url')
    op.drop_column('plant_species', 'default_image_url')
    op.drop_column('plant_species', 'max_width_ft')
    op.drop_column('plant_species', 'max_height_ft')
    op.drop_column('plant_species', 'hardiness_location')
    op.drop_column('plant_species', 'hardiness')
    op.drop_column('plant_species', 'indoor')
    op.drop_column('plant_species', 'tropical')
    op.drop_column('plant_species', 'invasive')
    op.drop_column('plant_species', 'thorny')
    op.drop_column('plant_species', 'salt_tolerant')
    op.drop_column('plant_species', 'drought_tolerant')
    op.drop_column('plant_species', 'watering')
    op.drop_column('plant_species', 'care_level')
    op.drop_column('plant_species', 'poisonous_to_pets')
    op.drop_column('plant_species', 'poisonous_to_humans')
    op.drop_column('plant_species', 'medicinal')
    op.drop_column('plant_species', 'cuisine')
    op.drop_column('plant_species', 'description')
    op.drop_column('plant_species', 'plant_type')
    op.drop_column('plant_species', 'other_names')
    # ### end Alembic commands ###
