"""add species_id to plants

Revision ID: 9fba25a7fa9d
Revises: 38032e57663d
Create Date: 2026-04-21 13:16:12.601625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fba25a7fa9d'
down_revision: Union[str, Sequence[str], None] = '38032e57663d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_species', sa.Column('external_species_id', sa.String(length=100), nullable=True))
    op.add_column('plant_species', sa.Column('scientific_name', sa.String(length=100), nullable=True))
    op.add_column('plant_species', sa.Column('common_name', sa.String(length=100), nullable=True))
    op.add_column('plant_species', sa.Column('life_cycle', sa.String(length=50), nullable=True))
    op.add_column('plant_species', sa.Column('sunlight_requirement', sa.String(length=255), nullable=True))
    op.add_column('plant_species', sa.Column('watering_interval_days', sa.Integer(), nullable=True))
    op.add_column('plant_species', sa.Column('recommended_soil', sa.String(length=255), nullable=True))
    op.add_column('plant_species', sa.Column('propagation_method', sa.String(length=255), nullable=True))
    op.add_column('plant_species', sa.Column('pest_susceptibility', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('plant_species_external_id_key'), 'plant_species', type_='unique')
    op.drop_column('plant_species', 'external_id')
    op.drop_column('plant_species', 'species_name')
    op.add_column('plants', sa.Column('species_id', sa.Integer(), nullable=True))
    op.add_column('plants', sa.Column('data_source', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.create_foreign_key(None, 'plants', 'plant_species', ['species_id'], ['id'])
    op.drop_column('plants', 'is_synced')
    op.drop_column('plants', 'external_species_id')
    op.drop_column('plants', 'source')
    op.drop_column('plants', 'species')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('species', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('external_species_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('is_synced', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.drop_column('plants', 'data_source')
    op.drop_column('plants', 'species_id')
    op.add_column('plant_species', sa.Column('species_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('plant_species', sa.Column('external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('plant_species_external_id_key'), 'plant_species', ['external_id'])
    op.drop_column('plant_species', 'pest_susceptibility')
    op.drop_column('plant_species', 'propagation_method')
    op.drop_column('plant_species', 'recommended_soil')
    op.drop_column('plant_species', 'watering_interval_days')
    op.drop_column('plant_species', 'sunlight_requirement')
    op.drop_column('plant_species', 'life_cycle')
    op.drop_column('plant_species', 'common_name')
    op.drop_column('plant_species', 'scientific_name')
    op.drop_column('plant_species', 'external_species_id')
    # ### end Alembic commands ###
