"""test change

Revision ID: a8620439b9bf
Revises: 2b8aacb11c5a
Create Date: 2026-04-18 14:38:01.898027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8620439b9bf'
down_revision: Union[str, Sequence[str], None] = '2b8aacb11c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_species_cache_id'), table_name='plant_species_cache')
    op.drop_table('plant_species_cache')
    op.add_column('soil_conditions', sa.Column('data_source', sa.String(length=50), nullable=True))
    op.drop_column('soil_conditions', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soil_conditions', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('soil_conditions', 'data_source')
    op.create_table('plant_species_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('species_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('plant_species_cache_pkey')),
    sa.UniqueConstraint('external_id', name=op.f('plant_species_cache_external_id_key'))
    )
    op.create_index(op.f('ix_plant_species_cache_id'), 'plant_species_cache', ['id'], unique=False)
    # ### end Alembic commands ###
