"""add edible and growth_rate to species

Revision ID: ae5430c11581
Revises: fa286759d136
Create Date: 2026-04-27 14:56:32.574596

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae5430c11581'
down_revision: Union[str, Sequence[str], None] = 'fa286759d136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_species', sa.Column('edible', sa.String(length=10), nullable=True))
    op.add_column('plant_species', sa.Column('growth_rate', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_species', 'growth_rate')
    op.drop_column('plant_species', 'edible')
    # ### end Alembic commands ###
