"""move environment_type to location and add plant_type

Revision ID: fa286759d136
Revises: 9fba25a7fa9d
Create Date: 2026-04-25 14:31:28.728814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa286759d136'
down_revision: Union[str, Sequence[str], None] = '9fba25a7fa9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('plant_type', sa.String(length=50), nullable=True))
    op.drop_column('plants', 'environment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('environment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('plants', 'plant_type')
    # ### end Alembic commands ###
